name: Run Analysis Pipeline # 工作流程名称
on: [push, pull_request] # 触发事件，这里设置为代码推送和拉取请求时触发

jobs:
  analyze: # 作业名称
    runs-on: ubuntu-latest # 运行环境，这里选择最新版 Ubuntu 系统
    steps:
      - name: Checkout code # 步骤名称
        uses: actions/setup-python@v4 # 使用官方的 setup-python 动作来设置 Python 环境
        with:
          python-version: '3.9' # 指定 Python 版本
      - name: Setup R # 安装 R 环境
        uses: r-lib/actions/setup-r@v2 # 使用 r-lib 提供的动作来设置 R 环境
      - name: Install Python dependencies # 安装 Python 依赖
        run: pip install -r environment/requirements.txt # 运行命令安装依赖，假设依赖文件在 environment/requirements.txt
      - name: Install R packages # 安装 R 包
        run: Rscript environment/install.R # 运行 R 脚本安装包，假设安装脚本在 environment/install.R
      - name: Run Python script # 运行 Python 脚本
        run: python scripts/python/scrape_data.py --output data/raw/tweets.csv # 运行 Python 脚本，假设脚本在 scripts/python/scrape_data.py
      - name: Run R script # 运行 R 脚本
        run: Rscript scripts/r/analyze_sentiment.R data/raw/tweets.csv data/processed/results.csv # 运行 R 脚本，假设脚本在 scripts/r/analyze_sentiment.R
      - name: Upload results # 上传结果
        uses: actions/upload-artifact@v3 # 使用官方的上传动作
        with:
          name: analysis-results # 结果名称
          path: data/processed/results.csv # 要上传的结果文件路径
